region             = "eu-west-3"
availability_zone1 = "eu-west-3a"
availability_zone2 = "eu-west-3b"
availability_zone3 = "eu-west-3c"
cluster-name = "terra-eks-cluster"
# aws_access_key = "FIXME"
# aws_secret_key = "FIXME"
